<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.16">
  <POU Name="FB_Void" Id="{28d1cb9f-6a8b-4c41-a79a-d873346e878b}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_Void
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
	pSequenceMaster : POINTER TO PVOID;
	fbConveyor : FB_Conveyor;
	fbVoidConveyor : FB_Conveyor;
	pConveyor : POINTER TO FB_Conveyor;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[pSequenceMaster := ADR(fbConveyor);

pConveyor := pSequenceMaster;]]></ST>
    </Implementation>
    <LineIds Name="FB_Void">
      <LineId Id="9" Count="0" />
      <LineId Id="12" Count="0" />
      <LineId Id="15" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>