<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.16">
  <POU Name="F_Concat6" Id="{db763e86-c055-4259-a945-37bf4098a381}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION F_Concat6 : STRING(255)
VAR_INPUT
	String1 : STRING(255);
	String2 : STRING(255);
	String3 : STRING(255);
	String4 : STRING(255);
	String5 : STRING(255);
	String6 : STRING(255);
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[F_Concat6 := F_Concat5(String2,String3,String4,String5,String6);
F_Concat6 := CONCAT(String1,F_Concat6);]]></ST>
    </Implementation>
    <LineIds Name="F_Concat6">
      <LineId Id="17" Count="0" />
      <LineId Id="7" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>